development:
  adapter: postgresql
  encoding: utf8
  database: divvy_trips
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: divvy_trips
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: divvy_trips
  pool: 5
  username:
  password: